export const TRANSFORM_VALUE_LOAD = 'TRANSFORM_VALUE_LOAD'
export const TRANSFORM_VALUE_SUCCESS = 'TRANSFORM_VALUE_SUCCESS'
export const TRANSFORM_VALUE_ERROR = 'TRANSFORM_VALUE_ERROR'
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION'